config/routes.rb
Rails.application.routes.draw do
  

  #resources :quiz_times
  #resources :questions
  resources :quizzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #rotas aninhadas para perguntas

  scope '/quizzes/:quiz_id/' do 
  	resources :questions
  end

  scope '/quizzes/:quiz_id/questions/:question_id/' do
    resources :fake_answers
  end

  #renomeando resource
  resources :quiz_time, controller: 'quiz_times'

  root "quizzes#index"

end

app/models/question.rb
class Question < ApplicationRecord
	#belongs_to :quiz
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @quiz = params[:quiz_id]
    @fake_answers = FakeAnswer.where(question_id: params[:id])
  end

  # GET /questions/new
  def new
    @quiz = Quiz.find(params[:quiz_id])
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    @quiz = Quiz.find(params[:quiz_id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @quiz = Quiz.find(params[:quiz_id])
    @question = Question.new(question_params) 
    #respond_to do |format|
      if @question.save
        link_quiz_question(@quiz, @question)
        #format.json { render :show, status: :created, location: @question }
      else
        redirect_to quizzes_path
        flash[:notice] = 'Falha em criar pergunta'
        #format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    #na real, cada question pertence a um quiz, basta achar a question de mesma id
    @qq = QuizQuestion.where(question: @question)
    @qq.destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:statement, :real_answer, :fake_answer, :quiz_id)
    end

    def link_quiz_question quiz, question
      @qq = QuizQuestion.new
      @qq.quiz = quiz
      @qq.question = question
      respond_to do |format|
        if @qq.save
          format.html{ redirect_to quizzes_path, notice: 'Pergunta associada ao questionário com sucesso'}
        else
          format.html{ redirect_to quizzes_path, notice: 'Falha ao associar pergunta ao questionário'}
        end
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :statement %>
    <%= form.text_field :statement %>
  </div>

  <div class="field">
    <%= form.label :real_answer %>
    <%= form.text_field :real_answer %>
  </div>

  <div class="field">
    <%= form.label :fake_answer %>
    <%= form.text_field :fake_answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', quizzes_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Statement</th>
      <th>Real answer</th>
      <th>Fake answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.statement %></td>
        <td><%= question.real_answer %></td>
        <td><%= question.fake_answer %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', quizzes_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statement:</strong>
  <%= @question.statement %>
</p>

<p>
  <strong>Real answer:</strong>
  <%= @question.real_answer %>
</p>

<p>
  <strong>Fake answer:</strong>
  <%= @question.fake_answer %>
</p>
<% if @fake_answers.count > 0 %>
  <% @fake_answers.each do |fa| %>
    <p>
      <strong>Fake answer:</strong>
      <%= fa.answer %>
    </p>
  <% end %>
<% end %>
<%= link_to 'New Fake Answer', new_fake_answer_path(@quiz,@question) %> |
<%= link_to 'Editar enunciado, resposta verdadeira ou primeira resposta falsa', edit_question_path(@question) %> |
<%= link_to 'Back', quizzes_path %>