config/routes.rb
Rails.application.routes.draw do
  

  #resources :quiz_times
  #resources :questions
  resources :quizzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #rotas aninhadas para perguntas

  scope '/quizzes/:quiz_id/' do 
  	resources :questions
  end

  scope '/quizzes/:quiz_id/questions/:question_id/' do
    resources :fake_answers
  end

  #renomeando resource
  resources :quiz_time, controller: 'quiz_times'

  root "quizzes#index"

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
    @questions
    @count
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @questions = get_questions
    @answers
    @count = -1
    @total_questions
    @new_quiz = Quiz.new
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    if params[:commit] == 'Avançar'
      @quiz = Quiz.find(params[:quiz_id])
      answer = params[:user_answ]

      answer = compare_answers @quiz, answer
      


      respond_to do |format|
        if answer >= 0.7
          format.html { redirect_to root_path, notice: "Muito bem!" }
        else
          format.html { redirect_to root_path, notice: "Você é muito feio!" }
        end
      end
    else 
      @quiz = Quiz.new(quiz_params)
      respond_to do |format|
        if @quiz.save
          format.html { redirect_to quizzes_path, notice: 'Quiz was successfully created.' }
          format.json { render :show, status: :created, location: @quiz }
        else
          format.html { render :new }
          format.json { render json: @quiz.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quizzes_path, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_questions_from quiz
    @qq = QuizQuestion.where(quiz: quiz)
    @questions = Array.new
    @qq.each do |q|
      @questions<<Question.find(q.question_id)
    end
    return @questions
  end
  helper_method :get_questions_from

  def count_answers question 
    return 2 +  FakeAnswer.where(question_id: question).count
  end
  helper_method :count_answers

  def get_answers question
    @answers = Array.new
    @answers << question.real_answer
    @answers << question.fake_answer
    another_fake_ones = FakeAnswer.where(question: question)
    another_fake_ones.each do |afo|
      @answers << afo.answer
    end
    return @answers
  end
  helper_method :get_answers

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      if params[:commit] != 'Avançar'  
        params.require(:quiz).permit(:name)
      else
        params.permit(:quiz_id, :user_answ)
      end
    end

    def get_questions
      qq = QuizQuestion.where(quiz_id: params[:id])
      @questions = Array.new
      qq.each do |q|
        @questions<<Question.find(q.question_id)
      end
      return @questions 
    end

    def coo
      return 1
    end

    def compare_answers quiz, answers
      questions = QuizQuestion.where(quiz: quiz)
      user_answers = Array.new
      percentage = 0
      #i = 1
      questions.each do |q|
        #if questions.count > 1 && i < questions.count
        if answers.include?("&<==>&")
          position = answers.index("&<==>&")
          question_answer = answers[0, position]
          answers = answers[position+6, answers.size-position-6] 
        else
          question_answer = answers
        end
        if Question.find(q.question_id).real_answer.eql? question_answer
          percentage +=1
        end
      end
      #percentage = percentage/questions.count
      

      return percentage.to_f/questions.count.to_f
    end

    
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', questions_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>
    <% @quizzes.each do |quiz| %>
      <div style="border: black 1px solid;">
        <div style="font-weight: bold;"><%= "Questionário: #{quiz.name}" %> - <%= link_to 'RESPONDER QUESTIONÁRIO', quiz_path(quiz)%>
        </div>
        <hr>
        <% @questions = get_questions_from(quiz) %>
        <% @count = 1 %>
        <% @questions.each do |q| %>
          <br>
          <%="#{@count}º - #{q.statement} - #{count_answers(q)} respostas"%> <%= link_to 'Mostrar Pergunta', question_path(quiz,q) %><br>
          
          
          <% @count+=1%>
        <% end %>
        <br>
        <br><%= link_to 'Nova Pergunta',  new_question_path(quiz) %>
        <br><%= link_to 'Edit', edit_quiz_path(quiz) %>
        <br><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %>

      </div>
    <% end %>
  


<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/quiz_evaluation.html.erb
Coo is here!

app/views/quizzes/show.html.erb
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head> 
<p id="notice"><%= notice %></p>
<%= form_with(model: @new_quiz, local: true) do |form| %>

	<p>
	  <strong>Name:</strong>
	  <%= @quiz.name %>
	</p>
	<br>
	
	<%# já é sabida a ordem das perguntas de um quiz, basta gaurdar o valor das respostas %>
	<% @questions.each do |q| %>
		<% @count+=1%>
		<p style="font-weight: bold;"><%= q.statement %></p>

		<% @answers = get_answers(q) %>
		<% @answers.shuffle.each do |a| %>
			<p><%= radio_button("#{@count}", "answer", a, onchange: "update_answers(#{@count}, this);") %><%= a %></p>
		<% end %>
		<!-- , onchange: "update_answers(#{@count}, this);" -->
		<br><br>
	<% end %>
	<input type="hidden" name="quiz_id" value=<%= @quiz.id %> >
	<input type="hidden" id="user_choices" name="user_answ" value="" >
	<% @total_questions = @count %>

	<%# o nome na tag é o commit %>
	<%= submit_tag("Avançar") %>
<% end %>



<%= link_to 'Back', quizzes_path %>



<script>
	var user_answers = Array();
	<% i = 0 %>
	<% while i <= @count do %>
		user_answers.push("0");
		<% i+=1%>
	<% end %>
	var i = 0;
	var answ = "";

	
	function update_answers(question_no, value){
		user_answers[question_no] = $(value).val();
		i = 0;
		var answ = "";
		for ( ; i<= <%=@total_questions%> ;i+=1){
			answ = answ+user_answers[i];
			if (i+1 <= <%=@count%> ){
				answ = answ+"&<==>&";
		  		} 
		   	}
		$("#user_choices").attr("value", answ);
	}

</script>