config/routes.rb
Rails.application.routes.draw do
  

  #resources :quiz_times
  #resources :questions
  resources :quizzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #rotas aninhadas para perguntas

  scope '/quizzes/:quiz_id/' do 
  	resources :questions
  end

  scope '/quizzes/:quiz_id/questions/:question_id/' do
    resources :fake_answers
  end

  #renomeando resource
  resources :quiz_time, controller: 'quiz_times'

  root "quizzes#index"

end

app/models/quiz_time.rb
class QuizTime < ApplicationRecord
end

app/controllers/quiz_times_controller.rb
class QuizTimesController < ApplicationController
  before_action :set_quiz_time, only: [:show, :edit, :update, :destroy]

  # GET /quiz_times
  # GET /quiz_times.json
  def index
    @quiz_times = QuizTime.all
  end

  # GET /quiz_times/1
  # GET /quiz_times/1.json
  def show
  end

  # GET /quiz_times/new
  def new
    @quiz_time = QuizTime.new
  end

  # GET /quiz_times/1/edit
  def edit
  end

  # POST /quiz_times
  # POST /quiz_times.json
  def create
    @quiz_time = QuizTime.new(quiz_time_params)

    respond_to do |format|
      if @quiz_time.save
        format.html { redirect_to @quiz_time, notice: 'Quiz time was successfully created.' }
        format.json { render :show, status: :created, location: @quiz_time }
      else
        format.html { render :new }
        format.json { render json: @quiz_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quiz_times/1
  # PATCH/PUT /quiz_times/1.json
  def update
    respond_to do |format|
      if @quiz_time.update(quiz_time_params)
        format.html { redirect_to @quiz_time, notice: 'Quiz time was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz_time }
      else
        format.html { render :edit }
        format.json { render json: @quiz_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quiz_times/1
  # DELETE /quiz_times/1.json
  def destroy
    @quiz_time.destroy
    respond_to do |format|
      format.html { redirect_to quiz_times_url, notice: 'Quiz time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz_time
      @quiz_time = QuizTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_time_params
      params.require(:quiz_time).permit(:questions, :correct_answers)
    end
end

app/helpers/quiz_times_helper.rb
module QuizTimesHelper
end

app/views/quiz_times/_form.html.erb
<%= form_with(model: quiz_time, local: true) do |form| %>
  <% if quiz_time.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz_time.errors.count, "error") %> prohibited this quiz_time from being saved:</h2>

      <ul>
      <% quiz_time.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :questions %>
    <%= form.text_field :questions %>
  </div>

  <div class="field">
    <%= form.label :correct_answers %>
    <%= form.text_field :correct_answers %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quiz_times/edit.html.erb
<h1>Editing Quiz Time</h1>

<%= render 'form', quiz_time: @quiz_time %>

<%= link_to 'Show', @quiz_time %> |
<%= link_to 'Back', quiz_times_path %>

app/views/quiz_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quiz Times</h1>

<table>
  <thead>
    <tr>
      <th>Questions</th>
      <th>Correct answers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quiz_times.each do |quiz_time| %>
      <tr>
        <td><%= quiz_time.questions %></td>
        <td><%= quiz_time.correct_answers %></td>
        <td><%= link_to 'Show', quiz_time %></td>
        <td><%= link_to 'Edit', edit_quiz_time_path(quiz_time) %></td>
        <td><%= link_to 'Destroy', quiz_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz Time', new_quiz_time_path %>

app/views/quiz_times/new.html.erb
<h1>New Quiz Time</h1>

<%= render 'form', quiz_time: @quiz_time %>

<%= link_to 'Back', quiz_times_path %>

app/views/quiz_times/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(model: quiz_time, local: true) do |form| %>

	<p>
	  <strong>Name:</strong>
	  <%= @quiz.name %>
	</p>
	<br>
	<% @questions.each do |q| %>
		<p style="font-weight: bold;"><%= q.statement %></p>

		<% @answers = get_answers(q) %>
		<% @answers.shuffle.each do |a| %>
			<p><%= radio_button("post", "category", a) %><%= a %></p>
		<% end %>

		<br><br>
	<% end %>
	<%= submit_tag("Avançar") %>
<% end %>

<%= link_to 'Back', quizzes_path %>