config/routes.rb
Rails.application.routes.draw do
  

  #resources :quiz_times
  #resources :questions
  resources :quizzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #rotas aninhadas para perguntas

  scope '/quizzes/:quiz_id/' do 
  	resources :questions
  end

  scope '/quizzes/:quiz_id/questions/:question_id/' do
    resources :fake_answers
  end

  #renomeando resource
  resources :quiz_time, controller: 'quiz_times'

  root "quizzes#index"

end

app/models/fake_answer.rb
class FakeAnswer < ApplicationRecord
  belongs_to :question
end

app/controllers/fake_answers_controller.rb
class FakeAnswersController < ApplicationController
  before_action :set_fake_answer, only: [:show, :edit, :update, :destroy]

  # GET /fake_answers
  # GET /fake_answers.json
  def index
    @fake_answers = FakeAnswer.all
  end

  # GET /fake_answers/1
  # GET /fake_answers/1.json
  def show
  end

  # GET /fake_answers/new
  def new
    @fake_answer = FakeAnswer.new
  end

  # GET /fake_answers/1/edit
  def edit
  end

  # POST /fake_answers
  # POST /fake_answers.json
  def create
    @fake_answer = FakeAnswer.new(fake_answer_params)
    @fake_answer.question_id = params[:question_id]
    respond_to do |format|
      if @fake_answer.save
        format.html { redirect_to question_path(params[:quiz_id], params[:question_id]), notice: 'Fake answer was successfully created.' }
        format.json { render :show, status: :created, location: @fake_answer }
      else
        format.html { render :new }
        format.json { render json: @fake_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fake_answers/1
  # PATCH/PUT /fake_answers/1.json
  def update
    respond_to do |format|
      if @fake_answer.update(fake_answer_params)
        format.html { redirect_to @fake_answer, notice: 'Fake answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @fake_answer }
      else
        format.html { render :edit }
        format.json { render json: @fake_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fake_answers/1
  # DELETE /fake_answers/1.json
  def destroy
    @fake_answer.destroy
    respond_to do |format|
      format.html { redirect_to fake_answers_url, notice: 'Fake answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fake_answer
      @fake_answer = FakeAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fake_answer_params
      params.require(:fake_answer).permit(:answer, :question_id, :quiz_id)
    end
end

app/helpers/fake_answers_helper.rb
module FakeAnswersHelper
end

app/views/fake_answers/_form.html.erb
<%= form_with(model: fake_answer, local: true) do |form| %>
  <% if fake_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fake_answer.errors.count, "error") %> prohibited this fake_answer from being saved:</h2>

      <ul>
      <% fake_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fake_answers/edit.html.erb
<h1>Editing Fake Answer</h1>

<%= render 'form', fake_answer: @fake_answer %>

<%= link_to 'Show', @fake_answer %> |
<%= link_to 'Back', question_path(params[:quiz_id],params[:question_id]) %>

app/views/fake_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fake Answers</h1>

<table>
  <thead>
    <tr>
      <th>Answer</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fake_answers.each do |fake_answer| %>
      <tr>
        <td><%= fake_answer.answer %></td>
        <td><%= fake_answer.question %></td>
        <td><%= link_to 'Show', fake_answer %></td>
        <td><%= link_to 'Edit', edit_fake_answer_path(fake_answer) %></td>
        <td><%= link_to 'Destroy', fake_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fake Answer', new_fake_answer_path %>

app/views/fake_answers/new.html.erb
<h1>New Fake Answer</h1>

<%= render 'form', fake_answer: @fake_answer %>

<%= link_to 'Back', question_path(params[:quiz_id],params[:question_id]) %>

app/views/fake_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @fake_answer.answer %>
</p>

<p>
  <strong>Question:</strong>
  <%= @fake_answer.question %>
</p>

<%= link_to 'Edit', edit_fake_answer_path(@fake_answer) %> |
<%= link_to 'Back', fake_answers_path %>